

export const markets = [
  {
    "name": "blackheath growers' market",
    "address": "cnr Great Western Highway and Gardiner Cres",
    "suburb": "Blackheath",
    "state": "NSW",
    "postcode": "2785",
    "phone": "02 4572 6260",
    "website": "http://www.blackcastleevents.com.au/",
    "rating": 2,
    "totalRatings": 1,
    "thumbnail": "http://i.imgur.com/wD5xbLA.jpg?1",
    "latitude": -33.633484,
    "longitude": 150.284722,
    "hours":{
      "mon": false,
      "tues": false,
      "wed": false,
      "thurs": false,
      "fri": false,
      "sat": false,
      "sun": "8am - 12pm",
    },
    "other": "Every second Sunday"
  },
  {
    "name": "bulli foragers market",
    "address": "Grevillea Park Road",
    "suburb": "Bulli",
    "state": "NSW",
    "postcode": "2516",
    "phone": "0477 109 132",
    "website": "http://www.foragersmarkets.com/",
    "rating": 3,
    "totalRatings": 1,
    "thumbnail": "http://i.imgur.com/qB9MqQs.jpg?1",
    "latitude": -34.329476,
    "longitude": 150.910453,
    "hours":{
      "mon": false,
      "tues": false,
      "wed": false,
      "thurs": false,
      "fri": false,
      "sat": false,
      "sun": "9am - 2pm",
    },
    "other": "Every Sunday"
  },
  {
    "name": "camden produce markets",
    "address": "Lower John Street",
    "suburb": "Camden",
    "state": "NSW",
    "postcode": "2570",
    "phone": "0477 224 881",
    "website": "http://www.camden.nsw.gov.au/visit/place/camden-fresh-produce-market",
    "rating": 4,
    "totalRatings": 1,
    "thumbnail": "http://i.imgur.com/E6Gy2n9.jpg",
    "latitude": -34.050258,
    "longitude": 150.693628,
    "hours":{
      "mon": false,
      "tues": false,
      "wed": false,
      "thurs": false,
      "fri": false,
      "sat": "7am - 12pm",
      "sun": false,
    },
    "other": "Every Saturday"
  },
  {
    "name": "carriageworks farmers' market",
    "address": "245 Wilson Street",
    "suburb": "Eveleigh",
    "state": "NSW",
    "postcode": "2015",
    "phone": "02 8571 9182",
    "website": "http://www.carriageworks.com.au/CARRIAGEWORKS-FARMERS-MARKET",
    "rating": 5,
    "totalRatings": 1,
    "thumbnail": "http://i.imgur.com/SZstmpd.jpg",
    "latitude": -33.894167,
    "longitude": 151.191571,
    "hours":{
      "mon": false,
      "tues": false,
      "wed": false,
      "thurs": false,
      "fri": false,
      "sat": "8am - 1pm",
      "sun": false,
    },
    "other": "Every Saturday"
  },
  {
    "name": "concord farmers' market",
    "address": "Crane Street",
    "suburb": "Concord",
    "state": "NSW",
    "postcode": "2137",
    "phone": "0418 11 22 35",
    "website": "http://www.concordfarmersmarket.com.au/",
    "rating": 1,
    "totalRatings": 1,
    "thumbnail": "http://i.imgur.com/81exrSJ.jpg",
    "latitude": -33.863523,
    "longitude": 151.111220,
    "hours":{
      "mon": false,
      "tues": false,
      "wed": false,
      "thurs": false,
      "fri": false,
      "sat": false,
      "sun": "9am - 1pm",
    },
    "other": "1st & 3rd Sundays"
  },
  {
    "name": "pyrmont growers' market",
    "address": "Pirrama Road",
    "suburb": "Pyrmont",
    "state": "NSW",
    "postcode": "2009",
    "phone": "0412 366 165",
    "website": "http://pyrmontgrowersmarket.com.au/",
    "rating": 4,
    "totalRatings": 1,
    "thumbnail": "http://i.imgur.com/6zdzw29.jpg?1",
    "latitude": -33.868120,
    "longitude": 151.196911,
    "hours":{
      "mon": false,
      "tues": false,
      "wed": false,
      "thurs": false,
      "fri": false,
      "sat": "7.30am - 12pm",
      "sun": false,
    },
    "other": "Every 4th Saturday"
  },
  {
    "name": "sydney sustainable markets",
    "address": "Taylor Squar, Intersection Bourke + Flinders Streets",
    "suburb": "Darlinghurst",
    "state": "NSW",
    "postcode": "2010",
    "phone": "0416 525 244",
    "website": "http://www.sydneysustainablemarkets.org/",
    "rating": 1,
    "totalRatings": 1,
    "thumbnail": "http://i.imgur.com/0UcSgJ5.jpg?1",
    "latitude": -33.880383,
    "longitude": 151.216903,
    "hours":{
      "mon": false,
      "tues": false,
      "wed": false,
      "thurs": false,
      "fri": false,
      "sat": "8am - 1pm",
      "sun": false,
    },
    "other": "Every Saturday"
  },
];
